[package]
name = "sqlx-macros"
version = "0.4.0-pre"
repository = "https://github.com/launchbadge/sqlx"
description = "Macros for SQLx, the rust SQL toolkit. Not intended to be used directly."
license = "MIT OR Apache-2.0"
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
]

[lib]
proc-macro = true

[features]
default = [ "runtime-async-std" ]

runtime-async-std = [ "sqlx/runtime-async-std" ]
runtime-actix = [ "sqlx/runtime-actix" ]
runtime-tokio = [ "sqlx/runtime-tokio", "lazy_static" ]

# database
mysql = [ "sqlx/mysql" ]
postgres = [ "sqlx/postgres" ]
sqlite = [ "sqlx/sqlite" ]

# type
bigdecimal = [ "sqlx/bigdecimal" ]
chrono = [ "sqlx/chrono" ]
time = [ "sqlx/time" ]
ipnetwork = [ "sqlx/ipnetwork" ]
uuid = [ "sqlx/uuid" ]
json = [ "sqlx/json", "serde_json" ]

[dependencies]
sqlx-rt = { path = "../sqlx-rt", version = "0.1.0-pre" }
dotenv = { version = "0.15.0", default-features = false }
futures = { version = "0.3.4", default-features = false, features = [ "executor" ] }
heck = "0.3"
proc-macro2 = { version = "1.0.9", default-features = false }
sqlx = { version = "0.4.0-pre", default-features = false, package = "sqlx-core", path = "../sqlx-core" }
serde_json = { version = "1.0", features = [ "raw_value" ], optional = true }
syn = { version = "1.0.16", default-features = false, features = [ "full" ] }
quote = { version = "1.0.2", default-features = false }
url = { version = "2.1.1", default-features = false }
lazy_static = { version = "1.4.0", optional = true }
